name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Read version from Git ref
        id: version
        shell: pwsh
        run: Write-Output "::set-output name=version::$($env:GITHUB_REF -replace '^refs/tags/v', '')"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Publish for Linux
        shell: pwsh
        run: >
          dotnet publish ChangelogAutomation --runtime linux-x64 --configuration Release --output ./publish.linux-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true
          && Set-Location ./publish.linux-x64
          && zip -r ../ChangelogAutomation-v${{ steps.version.outputs.version }}.linux-x64.zip *
      - name: Publish for macOS
        shell: pwsh
        run: >
          dotnet publish ChangelogAutomation --runtime osx-x64 --configuration Release --output ./publish.osx-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true
          && Set-Location ./publish.osx-x64
          && zip -r ../ChangelogAutomation-v${{ steps.version.outputs.version }}.osx-x64.zip *
      - name: Publish for Windows
        shell: pwsh
        run: >
          dotnet publish ChangelogAutomation --runtime win-x64 --configuration Release --output ./publish.win-x64 -p:PublishTrimmed=true -p:PublishSingleFile=true
          && Set-Location ./publish.win-x64
          && zip -r ../ChangelogAutomation-v${{ steps.version.outputs.version }}.win-x64.zip *

      - name: Prepare a NuGet package
        run: dotnet pack --configuration Release -p:Version=${{ steps.version.outputs.version }}

      - name: Read changelog
        id: changelog
        run: dotnet run --project ChangelogAutomation -- ./CHANGELOG.md --outputFilePath ./release-data.md

      - name: Create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ChangelogAutomation v${{ steps.version.outputs.version }}
          body_path: ./release-data.md

      - name: 'Upload distribution: Linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: ChangelogAutomation-v${{ steps.version.outputs.version }}.linux-x64.zip
          asset_path: ./ChangelogAutomation-v${{ steps.version.outputs.version }}.linux-x64.zip
          asset_content_type: application/zip
      - name: 'Upload distribution: macOS'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: ChangelogAutomation-v${{ steps.version.outputs.version }}.osx-x64.zip
          asset_path: ./ChangelogAutomation-v${{ steps.version.outputs.version }}.osx-x64.zip
          asset_content_type: application/zip
      - name: 'Upload distribution: Windows'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: ChangelogAutomation-v${{ steps.version.outputs.version }}.win-x64.zip
          asset_path: ./ChangelogAutomation-v${{ steps.version.outputs.version }}.win-x64.zip
          asset_content_type: application/zip

      - name: Upload .nupkg file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_name: ChangelogAutomation.MSBuild.${{ steps.version.outputs.version }}.nupkg
          asset_path: ./ChangelogAutomation.MSBuild/bin/Release/ChangelogAutomation.MSBuild.${{ steps.version.outputs.version }}.nupkg
          asset_content_type: application/zip

      - name: Push a package to NuGet
        run: dotnet nuget push ./ChangelogAutomation.MSBuild/bin/Release/ChangelogAutomation.MSBuild.${{ steps.version.outputs.version }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
